# Generated by Django 4.1.3 on 2022-12-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.URLField(max_length=1000),
        ),
    ]
